language: python
python:
  - "2.7"
  - "3.2"
install:
  - pip install django redis --use-mirrors
script:
  - cd testing; python runtests.py test
notifications:
  email:
    recipients:
      - niwi@niwi.be
    on_success: change
    on_failure: change
