language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="https://www.djangoproject.com/download/1.7c2/tarball/"
  - DJANGO="django==1.6.3"
  - DJANGO="django==1.5.7"
  - DJANGO="django==1.4.12"

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django==1.4.12"
    - python: "3.4"
      env: DJANGO="django==1.4.12"

install:
  - pip install $DJANGO --use-mirrors
  - pip install redis==2.10.3 --use-mirrors

script:
  - (cd tests && python runtests.py -v2)
  - (cd tests && python runtests-sharded.py -v2)
  - (cd tests && python runtests-herd.py -v2)

services:
  - redis-server

notifications:
  email:
    recipients:
      - niwi@niwi.be
    on_success: change
    on_failure: change
